resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: env
  namespace: ${NAMESPACE}
  behavior: merge
  envs:
  - .env

- name: clamav
  namespace: ${NAMESPACE}
  behavior: merge
  envs:
  - .clamav.env